name: Build Reader Image  

on:
    release:
        types: [published]

jobs:
  job1:
    name: Build-Openjdk-8
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - name: Set Version
        id: set-version
        run: |
          echo "::set-output name=version::${GITHUB_REF:10}"
          echo "ReleaseTag=${GITHUB_REF:10}"

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Buildx-Openjdk-8
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v6
            linux/arm/v7
            linux/386
            linux/ppc64le
            linux/s390x
          push: true
          build-args: |
            VERSION=${{ steps.set-version.outputs.version }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/reader:${{ steps.set-version.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/reader:latest

  job2:
    name: Build-Openj9
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - name: Set Version
        id: set-version
        run: |
          echo "::set-output name=version::${GITHUB_REF:10}"
          echo "ReleaseTag=${GITHUB_REF:10}"

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Buildx-Openj9
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Openj9.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
            linux/ppc64le
            linux/s390x
          push: true
          build-args: |
            VERSION=${{ steps.set-version.outputs.version }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/reader:openj9-${{ steps.set-version.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/reader:openj9-latest

  job3:
    needs: [job1, job2]
    name: Docker Hub Description
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/reader
          short-description: 支持PUID，PGID，Umask设置的Reader镜像
          readme-filepath: ./README.md